spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/forum?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    database: 0 # Redis数据库索引（默认为0）,如果设置为1，那么存入的key-value都存放在select 1中
    port: 6379
    max-wait: 30000    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-active: 100   # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 20     # 连接池中的最大空闲连接
    min-idle: 0     # 连接池中的最小空闲连接
    timeout: 10000   # 连接超时
    password: 123456 # 密码,默认密码为空
#  data:
#    elasticsearch:
#      # 配置集群名
#      # 访问 es服务端 `http://127.0.0.1:9200/` 填写 `cluster_name` 对应的值
#      cluster-name: elasticsearch
#      # 配置节点信息，逗号分隔，如果没有指定，则启动ClientNode 【 注：9200->图形界面端、9300->程序端 】
#      # 开启 Elasticsearch 仓库(默认值:true)
#      repositories:
#        enabled: true
#  swagger:
#    enabled: true
  servlet:
    multipart:  # 此处设置请求文件的最大大小 否则SpringBoot默认不允许上传大于 10Mb 的文件 即1.25MB
      max-file-size: 2MB
      max-request-size: 2MB

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  config: classpath:log/logback-spring.xml

server:
  port: 9090

# JWT 密钥 此处PT8H 写法是参照Java 1.8的 Duration类
# D - 天 H - 小时 M - 分钟 S - 秒
# power是指在refreshToken的剩余时间小于几倍的accessToken时需要刷新refreshToken
jwt:
  secretKey: 81896169rocket
  accessTokenExpireTime: PT2H
  refreshTokenExpireTime: PT10H
  issuer: zp
  power: 2


